### ISSUE TITLE
App route link without reload or showing two routes simultaneously

### ISSUE THREAD

**Issue by garethbjohnson** [single-spa/single-spa-layout#103]
**Describe the bug or question**
I want to add a link from my default route to a route with an app. However, using the `singleSpaNavigate` code in the [`navigateToUrl` docs](https://single-spa.js.org/docs/api/#navigatetourl) causes a reload. When I prevent the reload, it briefly shows both routes at the same time before navigating.

How can I prevent a reload without showing both routes simultaneously?

**To Reproduce**
1. Pull [this example repo](https://github.com/garethbjohnson/single-spa-buggy-demo)
2. Run `yarn`
3. Run `yarn start` in both the `root-config` and `app` folders in different terminals
4. Go to `localhost:9000`
5. Click the first link to see the reload
6. Click the second link to see both routes briefly appear simultaneously

These are the steps I took to make the repo:
1. Followed the [quick start docs](https://single-spa.js.org/docs/getting-started-overview#quick-start) to make a root config with Layout Engine and an app with React
2. Used this template in the root config `index.ejs`:
```html
<template id="single-spa-layout">
  <single-spa-router>
    <route default>
      <h1>Home</h1>
      <ul>
        <li>
          <a href="/app" onclick="singleSpaNavigate()">Link 1 (causes reload)</a>
        </li>
        <li>
          <a href="#" onclick="singleSpaNavigate('/app')">Link 2 (briefly shows two routes simultaneously)</a>
        </li>
      </ul>
    </route>

    <route path="app">
      <h1>App</h1>
      <application name="@buggy-demo/app"></application>
    </route>
  </single-spa-router>
</template>
```

**Expected behavior**
I expected clicking each link to show the app route without a reload or showing both routes at once.

**Screenshots and/or console output**
Here is a demo of the buggy behaviour, where Link 1 uses the documented `singleSpaNavigate` approach and Link 2 uses `href="#"` to prevent a reload:

[bug demo](https://user-images.githubusercontent.com/5997302/103928285-873bbe00-5113-11eb-8afd-4a7a5c313082.mov)

You can briefly see the app heading below the default route content.

**Comment by joeldenning** [comment]
I've created https://github.com/single-spa/single-spa-layout/pull/104 which fixes the bug.

**Comment by joeldenning** [comment]
The fix for this is released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.4.0
