### ISSUE TITLE
export 'default' (imported as 'e') was not found in 'single-spa' using Webpack 5

### ISSUE THREAD

**Issue by jsmapr1** [single-spa/single-spa-layout#107]
Webpack throws a build error when importing `single-spa` into `single-spa-layout`. See #93 as a reference.

With index.js file like this (copied from docs):

```javascript
import { registerApplication, start } from "single-spa";
import {
  constructApplications,
  constructRoutes,
  constructLayoutEngine,
} from "single-spa-layout";

const routes = constructRoutes(document.querySelector("#single-spa-layout"));
const applications = constructApplications({
  routes,
  loadApp({ name }) {
    return System.import(name);
  },
});
const layoutEngine = constructLayoutEngine({ routes, applications });

applications.forEach(registerApplication);
start();
```

A build using webpack version 5 throws this warning:

```
ERROR in ./node_modules/single-spa-layout/dist/esm/single-spa-layout.min.js 2:3488-3514
export 'default' (imported as 'e') was not found in 'single-spa' (possible exports: BOOTSTRAPPING, LOADING_SOURCE_CODE, LOAD_ERROR, MOUNTED, MOUNTING, NOT_BOOTSTRAPPED, NOT_LOADED, NOT_MOUNTED, SKIP_BECAUSE_BROKEN, UNMOUNTING, UPDATING, addErrorHandler, checkActivityFunctions, ensureJQuerySupport, getAppNames, getAppStatus, getMountedApps, mountRootParcel, navigateToUrl, pathToActiveWhen, registerApplication, removeErrorHandler, setBootstrapMaxTime, setMountMaxTime, setUnloadMaxTime, setUnmountMaxTime, start, triggerAppChange, unloadApplication, unregisterApplication)
```

Webpack 4 will build, but will display the following error:

```
WARNING in ./node_modules/single-spa-layout/dist/esm/single-spa-layout.min.js 2:3488-3497
"export 'default' (imported as 'e') was not found in 'single-spa'
 @ ./index.js
```

Minimal reproducable example found here:
https://github.com/jsmapr1/single-spa-layout-minimal

**Comment by joeldenning** [comment]
Thanks, this kind of bug is a pretty frustrating one because it's related to trying to get single-spa-layout to work in as many environments as possible, but the js module / bundler ecosystem being a bit of a mess so sometimes it's tricky to get it work in node, webpack 4, webpack 5, rollup, parcel, esbuild, etc. I'll take a look at this in the next few days.

**Comment by jsmapr1** [comment]
Thanks I appreciate it!

**Comment by joeldenning** [comment]
The root cause of this is that we should really publish a major release of single-spa with `type` set to `module` or `exports` defined in the package.json. But I've been resistant to that because it would be a meaningless major release, and people would be disappointed in it.

**Comment by joeldenning** [comment]
I've created #108 with a workaround that works in webpack 5 and doesn't require publishing breaking versions of single-spa-layout and single-spa.

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.3.1
