### ISSUE TITLE
Uncaught exception error in console while using Layout Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by ajaybeniwal** [single-spa/single-spa-layout#113]
Im setting up Single-Spa-Layout with Index.ejs but keep on getting below error in console even though the registered route works fine, i am using template method to register my layout and for testing i have just kept one route in the page

```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at X (single-spa-layout.min.js:2)
    at b (single-spa-layout.min.js:2)
    at reroute.js:92
```

```
<template id="single-spa-layout">
--
  | <single-spa-router>
  | <div class="wrapper">
  | <section class="main-content" id="app">
  |  
  | <route path="ecp/ordersui/ibxservices">
  | <application name="@ecp/ibxservices" loader="commonLoader" props="user"></application>
  | </route>
  |  
  | </section>
  | </div>
  | </single-spa-router>
  | </template>
```

```
const userProfile = await axios.get('/api/ecp/users/getProfile');
	// eslint-disable-next-line no-undef
	await System.import('@ecp/styleguide');
	sessionStorage.setItem('uecp_locale', 'en_us');
	const layoutData = {
		loaders: {
			commonLoader: `<div>Loading....</div>`,
		},
		props: {
			user: userProfile.data,
		},
	};

	const routes = constructRoutes(document.querySelector('#single-spa-layout'), layoutData);
	const applications = constructApplications({
		routes,
		loadApp({ name }) {
			// eslint-disable-next-line no-undef
			return System.import(name);
		},
	});
	constructLayoutEngine({ routes, applications });
	applications.forEach(registerApplication);
	start();
```

**Comment by joeldenning** [comment]
This probably indicates that you're using an old version of single-spa. Try upgrading single-spa in your import map.

Here's the relevant code:

https://github.com/single-spa/single-spa-layout/blob/83c32e579547e8d79785a273ab88f7be1f389fca/src/browser/constructLayoutEngine.js#L402-405

https://github.com/single-spa/single-spa-layout/blob/83c32e579547e8d79785a273ab88f7be1f389fca/src/browser/constructLayoutEngine.js#L134

https://github.com/single-spa/single-spa-layout/blob/83c32e579547e8d79785a273ab88f7be1f389fca/src/browser/constructLayoutEngine.js#L194

**Comment by ajaybeniwal** [comment]
@joeldenning  i am  using the latest versions for both the packages
"single-spa": "5.9.0",
"single-spa-layout": "1.4.0",

**Comment by filoxo** [comment]
The versions in the package.json isn't relevant. You should ensure the correct versions in the **import map** which resides in the root-config.

**Comment by ajaybeniwal** [comment]
@joeldenning @filoxo   sorry i totally forgot that i have configured single-spa as external in my import-map , yes it got fixed after upgrading the version in import-map

**Comment by filoxo** [comment]
Glad you got the right version figured out! Forgetting the location of modules between local and in-browser is definitely something that happens regularly, no need to apologize. 🙂
