### ISSUE TITLE
Top-level default route and nested default route both load their applications, when only the top-level one should.

### ISSUE THREAD

**Issue by MartinManev** [single-spa/single-spa-layout#119]
**Describe the bug or question**
Hi. I stumbled upon this unexpected behavior and wanted to see if this is indeed a bug or not.

**To Reproduce**
1. Clone https://github.com/react-microfrontends/root-config
2. Open `src/index.ejs` and change the routes to:
```
<single-spa-router>
  <route path="nested">
    <route default>
      <h1>NESTED DEFAULT</h1>
      <application name="@react-mf/planets"></application>
    </route>
  </route>
  <route default>
    <h1>TOP-LEVEL DEFAULT</h1>
    <application name="@react-mf/people"></application>
  </route>
</single-spa-router>
```
3. Run development server and look at network requests in the browser:
- If you visit `/nested`, then only the `planets` app is loaded.
- If you visit `/`, then both `planets` and `people` apps are loaded. Any javascript they come with is executed. Probably CSS too.

**Expected behavior**
The top-level default route should only load the `people` application, and not both.

**Screenshots and/or console output**
Nested:
![Screenshot from 2021-02-25 13-27-10](https://user-images.githubusercontent.com/16416643/109147083-46544300-776d-11eb-9b43-65d32fb56718.png)
Top-level:
![Screenshot from 2021-02-25 13-27-25](https://user-images.githubusercontent.com/16416643/109147093-4a806080-776d-11eb-926b-7dcbece4f60b.png)

**Additional context**

**Comment by joeldenning** [comment]
I've fixed this in #120

**Comment by joeldenning** [comment]
Fix is released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.4.2

**Comment by MartinManev** [comment]
Thank you for the fix.
