### ISSUE TITLE
iFrame content and single-spa popstate

### ISSUE THREAD

**Issue by MattInternet** [single-spa/single-spa-layout#123]
We're using the single-spa-html helper to attempt to render another app in an iframe and it refreshes whenever the URL changes via `pushState` or `replaceState`.

**To Reproduce**
We're using the `single-spa-html` helper which lets you define an html template and renders it.

Our template looks pretty much like this:
```
template: (props) => {
   return `<iframe id="whatever" src="https://www.youtube.com/embed/owsfdh4gxyc" sandbox="allow-popups allow-same-origin allow-scripts" style="position: absolute; height: 100%; width: 100%; border: none"></iframe>`;
  }
```
This is set to render on the default route using the Layout Engine but the issue exists without using layout engine as well. It works pretty well until the url of the parent application, the single-spa application, changes at which point the iframe refreshes. We can see the iFrame firing its onload function and everything. This refresh behaviour does NOT happen if we just throw the iframe in an html file and call `window.history.pushState(null, "title", ["/anything"])` which makes me think its caused by the popstate event that single-spa fires whenever `pushState` / `replaceState` are called.

**Expected behavior**
We should be able to update the URL without it making our content refresh. I know single-spa relies heavily on its artificial popState event but is there anyway to shield its effects from certain parts of the app?

**Further Context**
We have also tried adding an iFrame to other single-spa applications and it appears that regardless of how it is added any iFrames in the entire app will refresh whenever single-spa fires its popState event

**Comment by adam-joseph** [comment]
Here is a repo demonstrating the behavior. I don't think it's specific to iframes, but using them does give a visual indication that the iframe has been removed and reloaded whenever a pushState is triggered. On this example I'm using the 'default' attribute on a route so I would expect the html-helper application to stay mounted regardless of the route I visit. Let me know if anything needs clarification, and thank you! https://github.com/adam-joseph/single-spa-layout-engine-demo

**Comment by joeldenning** [comment]
Thanks for providing the demonstration, it was very helpful in diagnosing the issue. I've put together a fix in https://github.com/single-spa/single-spa-layout/pull/125

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.5.1
