### ISSUE TITLE
Can't import from 'single-spa-layout/server'

### ISSUE THREAD

**Issue by jrajput** [single-spa/single-spa-layout#145]
Hi,

I am trying to use server side rendering in our typescript application and after installing version '^1.6.0' I am not able to import 'constructServerLayout' and 'sendLayoutHTTPResponse' from 'single-spa-layout/server' in a .ts file.
Error - 'can nnot find module 'single-spa-layout/server'

Please let me know why this is happening.
Thanks,
Jaideep.

**Comment by joeldenning** [comment]
You need to use a version of NodeJS and typescript that supports [package entrypoints](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packages_package_entry_points). See the code below https://github.com/single-spa/single-spa-layout/blob/50b691858e172366eb9758cfb1d5a30d99c6c5ca/package.json#L15

So if you're using ts-node, you should check whether it supports package entrypoints.

**Comment by lipsumar** [comment]
I'm using typescript `4.5.0-beta` which supports package entrypoints exports, according to [this](https://github.com/microsoft/TypeScript/issues/33079). My `compilerOptions.module` is set to `node12` and `moduleResolution` left undefined.

With this configuration, I'm getting `Could not find a declaration file for module 'single-spa-layout/server'.`

To fix this, i had to add a `"types"` entry in single-spa-layout package.json, so it would read as follow:
```
  "exports": {
    ".": {
      "default": {
        "import": "./dist/esm/single-spa-layout.min.js",
        "require": "./dist/umd/single-spa-layout.min.cjs"
      }
    },
    "./server": {
      "node": {
        "import": "./dist/esm/single-spa-layout-server.min.js",
        "require": "./dist/umd/single-spa-layout-server.min.cjs",
        "types": "./dist/types/single-spa-layout-server.d.ts" <<< This was added manually
      }
    }
  },
```

After doing so, I got the following error when building:

```
TS1471: Module 'single-spa-layout/server' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.
```

I can then get it to build by importing it like this, but it's clearly not how it should work:

```ts
import('single-spa-layout/server').then(({ constructServerLayout }) => {
  console.log(constructServerLayout);
});
```

Is it possible the server flavour is not yet usable with typescript ? Any pointer is welcome.
