### ISSUE TITLE
Error at render errors on layout engine

### ISSUE THREAD

**Issue by kloehz** [single-spa/single-spa-layout#147]
Hi, thanks u for awesome lib, i have the next problem, i have a navbar whit two micro-frontends, just one is up, when i render the downed, it say:

`mount-parcel.js:66 Uncaught (in promise) Error: single-spa minified message #5: See https://single-spa.js.org/error/?code=5&arg=`

but y rendered a string, here some pics:

![5](https://user-images.githubusercontent.com/67805554/129202706-efc7bfbb-2439-4b5f-b970-34b0de716664.png)
![4](https://user-images.githubusercontent.com/67805554/129202713-aba8e992-6a68-4410-ac79-16e79c2c63bd.png)
![3](https://user-images.githubusercontent.com/67805554/129202718-1e9ca3e0-d08d-4b22-9d53-1d75ed1c6928.png)
![1](https://user-images.githubusercontent.com/67805554/129202725-6fa62d7c-db86-46a0-bf84-271a9b9f3c62.png)
![2](https://user-images.githubusercontent.com/67805554/129202721-a018a21a-006e-4a3d-bbb7-6d3327095e7f.png)

P.D: if i join in the error route it render correctly, but if i join in other route and back, it crash again. Sorry for my bad english xd

**UPDATE**: I found the 'error', if you do not pass a loader, the error breaks, you want to close the issue, no problem for me, if this is not a bug it would be good to put it in the documentation, thank you very much! :D

**Comment by kloehz** [comment]
sorry, u can close the issue, i resolved it

the error appear when i **set error and not set loader!**, i dont know if it is a bug, but here is the solution :D

thanks u for all :)

**Comment by frehner** [comment]
Closing per request.
