### ISSUE TITLE
Latest stable version `2.0.1` depends on `single-spa@6` that is still in beta

### ISSUE THREAD

**Issue by alex-enchi** [single-spa/single-spa-layout#158]
Hello

I started to update dependencies, and was quite happy to see major update of the layout library
But it depends on `single-spa@6` and at the moment of writing latest `single-spa` version is [v6.0.0-beta.2](https://github.com/single-spa/single-spa/releases/tag/v6.0.0-beta.2)

I do not think that it's safe to have unstable dependencies

**Comment by joeldenning** [comment]
Yes that's because single-spa@2 doesn't work without some features in single-spa@6. Single-spa 6 is solid and will be released as the official version at some point.
