### ISSUE TITLE
Exact match doesn't work for /

### ISSUE THREAD

**Issue by billysmt** [single-spa/single-spa-layout#174]
I'm attempting to create a Layout with a home page and error page for un-recognized route.  My attempted layout is as follows.

```
<single-spa-router>
  <nav>
    <application name="@SMT/demo-ui-navbar" loader="topNav" error="topNav"></application>
  </nav>
  <route path="/help">
    <h1>Help</h1>
    <application name="@SMT/demo-ui-help"></application>
  </route>
  <route path="/" exact>
    <application name="@SMT/demo-ui-homepage"></application>
  </route>
  <route default>
    <h1>404 Not Found</h1>
  </route>
</single-spa-router>
```

Assumption:
That /help would show the help content, / would show the homepage and then a non-matched route would show my 404.

Behavior:
Home page shows up on all routes, not just /.  Unable to trigger the error page on an unsupported route.

**Comment by MilanKovacic** [comment]
Hi @billysmt, have you been able to resolve the issue?

**Comment by billysmt** [comment]
I'm no longer on this just of the project but I believe a solution was found to this problem

**Comment by MilanKovacic** [comment]
Closing the issue. If you encounter any other problems, feel free to open a new issue.
