### ISSUE TITLE
 Module '"single-spa-layout"' has no members exported 'matchRoute'.

### ISSUE THREAD

**Issue by levymateus** [single-spa/single-spa-layout#188]
Hello. In the cocumentation, we have a function [matchRoute()](https://single-spa.js.org/docs/layout-api#matchroute). 
But, this function is not exported in [single-spal-layout.js](https://github.com/single-spa/single-spa-layout/blob/main/src/single-spa-layout.js) file.

**Comment by joeldenning** [comment]
Fixed in https://github.com/single-spa/single-spa-layout/releases/tag/v2.2.0
