### ISSUE TITLE
Error UI breaks MF after handling LOAD_ERROR status by retry to load module

### ISSUE THREAD

**Issue by rafffa** [single-spa/single-spa-layout#209]
**Describe the bug or question**
Handling LOAD_ERROR status to re-attempt to download the module doesn't correctly work when [ErrorUI](https://single-spa.js.org/docs/layout-definition#error-uis) is shown.

**To Reproduce**
It can be reproduced on https://github.com/react-microfrontends/root-config project by few steps:

1. we should add `Error UI` to one of the application, for example for "@react-mf/people"
so in `index.ejs` template would be like this:
```
        <route path="people">
          <application name="@react-mf/people" loader="topNav" error="topNav"></application>
        </route>
```

2. next we need to simulate a loading error, to do so I've used import maps override tool
you can use any working MF to override `@react-mf/people`

3. shut down your MF so it cann't be downloaded 

4. reload http://localhost:9000/ with overrided `@react-mf/people` MF

5. navigate by nav menu to `/people` route (you would see error UI, for this case it would be `Failed to load topnav`)

6. turn on overrided MF server

7. run script in Console: 
```
System.import("single-spa").then((spa) => {
    System.delete(System.resolve("@react-mf/people"));
    spa.unloadApplication("@react-mf/people");
})
```

8. overrided MF should be successfully loaded and rendered

9. try to navigate somewhere, for example to `/planets` by nav menu 

10. we get error: `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

11. returning back to `/planets` doesn't works correctly, we have empty DOM in applications node

**Expected behavior**
Reloading application when Error UI is shown doesn't break an application

**Comment by joeldenning** [comment]
Fix for this released in [single-spa-layout@3.0.0](https://single-spa.slack.com/archives/C9JV40F7V/p1726982044053799)
