### ISSUE TITLE
RTL/LTR Layouts + other layout related states

### ISSUE THREAD

**Issue by pkhodaveissi** [single-spa/single-spa-layout#27]
Maybe an observable obj containing such state passed to each micro-app with methods to alter it.

But I wouldn't overcomplicate the single-spa-layout lib, instead could've made a utility micro-app, responsible for creating and altering the state obj, initialize it inside single-spa-layout and then pass it to micro-apps.

only thoughts here.

@joeldenning please advise.

**Comment by joeldenning** [comment]
I haven't done LTR/RTL layouts before and need think think more about this one. Passing props to the microfrontends is fairly easy, but changing the dom order of the applications themselves could get tricky.

> Maybe an observable obj containing such state passed to each micro-app with methods to alter it.
> But I wouldn't overcomplicate the single-spa-layout lib, instead could've made a utility micro-app, responsible for creating and altering the state obj, initialize it inside single-spa-layout and then pass it to micro-apps.

Yes I think that this approach sounds sensible. The single-spa-layout library will be part of the root-config and will allow you to specify any props you'd like for single-spa applications.

**Comment by pkhodaveissi** [comment]
If you have no pre-exp with RTL, this lib and its source code can really help you understand the nitty-gritty parts of it:
https://github.com/alitaheri/jss-rtl

**Comment by joeldenning** [comment]
Is it common for the dom order to be different for LTR vs RTL? I am thinking about scenarios where navigation menus might be in a different position on the screen depending on LTR/RTL, and whether dom order ever changes for that so that screen readers read the information correctly. Or also other scenarios where for LTR you'd want app1 then app2 in the dom, but for RTL you'd want app2 then app1 in the dom.

**Comment by pkhodaveissi** [comment]
@joeldenning, good question, no it's not common.

since the standard way of going RTL is by setting the `dir` on the `body` tag like so: ```<body dir="rtl">```
the order of dom tree will not change and the browser(dom renderer) will handle moving things around for you, therefore only elements with fixed and absolute(and such) positioning need to be managed explicitly with the CSS. That would cross the navigation menus case.

For the case when someone might need app1 then app2 or vice versa in different layout directions,  In my language which is Persian, I haven't seen such a case so far, if we want two parts of a page, let's call them app1 and app2, to appear in the dom with some order in LTR mode, then we'd want them with the same order while the page is in RTL. The order of the dom is something we don't mess around with, while the CSS and positioning is the way to go about this.

Please do ask anything that pops or you may find amiss.

**Comment by joeldenning** [comment]
👍 thanks for the clarification. It sounds like single-spa props may be sufficient then, in this case, and that single-spa-layout will not need to do anything special to support this. As such, I am closing this for now. However, feel free to reopen / comment further if something else comes up.
