### ISSUE TITLE
Support defining dom elements in JSON

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-layout#40]
We already almost support this by supporting parse5's json representation of dom elements. However we should extend that to support that json representation in browsers, too (not just node)

**Comment by jefferson-gaivota** [comment]
Hello, any prevision when this will become available?

**Comment by joeldenning** [comment]
No, there is no set timeline for this. I am working on other endeavors right now and do not know when I will come back to this. If you have interest in the feature, I'd be happy to talk through the implementation with you and review pull requests.

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.0.0-beta.9 and documented in https://single-spa.js.org/docs/layout-definition#json-dom-nodes
