### ISSUE TITLE
How to activate application on "/" path only?

### ISSUE THREAD

**Issue by fabiomilheiro** [single-spa/single-spa-layout#46]
There's a `single-spa-router` element:

```html
  <template id="single-spa-layout">
    <single-spa-router>
      <application name="@pikabytes/admin-top-navigation"></application>
      <route path="/">
        <application name="@pikabytes/admin-dashboard"></application>
      </route>
      <route path="/content">
        <application name="@pikabytes/admin-content"></application>
      </route>
      <application name="@pikabytes/admin-bottom-navigation"></application>
    </single-spa-router>
  </template>
```

The content app is successfully activated when the path is "/content" but the dashboard is always available.

How do I activate the dashboard app only for the "/"?

**Comment by joeldenning** [comment]
Good question - currently that is not possible. However, I think it would be a good thing to add. Perhaps an `exact` attribute that indicates that it should not be used as a prefix.

single-spa-layout uses single-spa's [`pathToActiveWhen`](https://single-spa.js.org/docs/api#pathtoactivewhen) function to generate an [activity function](https://single-spa.js.org/docs/configuration/#activity-function) from the string. To implement this, the best thing might be to add an argument to that function that indicates whether it should be used as a prefix or not. If you have interest in implementing this, that would be greatly appreciated. The first PR would be to single-spa, and then the second PR here to single-spa-layout.

**Comment by joeldenning** [comment]
This was accidentally closed due to a mistaken commit message - reopening it now. We should support this.

**Comment by joeldenning** [comment]
Maybe something like this:

```html
<route path="/" exact="true">
```

```json
{
  "type": "route",
  "path": "/",
  "exact": true
}
```

**Comment by fabiomilheiro** [comment]
Thanks, @joeldenning. Appreciate your answer. And apologies, I must have forgotten to reply.

That time, as I remember it, I worked around it using "/#dashboard" but I like the exact attribute.

Cheers!

**Comment by joeldenning** [comment]
Reopening, as this is something that I'd like to have implemented.

**Comment by caioaletrocadock** [comment]
I'm interested in that option too.

**Comment by joeldenning** [comment]
I created https://github.com/single-spa/single-spa/pull/694 which is required to implement this. I'll also work on the corresponding changes here in single-spa-layout.

**Comment by joeldenning** [comment]
#102 implements this in single-spa-layout. It relies on the single-spa change. I've also created a documentation PR at https://github.com/single-spa/single-spa.js.org/pull/388
