### ISSUE TITLE
Error: The HTMLElement passed to constructRoutes must be <single-spa-router>. Received TEMPLATE

### ISSUE THREAD

**Issue by jimmyandrade** [single-spa/single-spa-layout#51]
## Steps to reproduce this bug

1. Create a `single-spa`-based project following [root-config](https://github.com/react-microfrontends/root-config);
2. Run `npm start`.

## Environment

This bug was reproduced at this repo:
https://github.com/natura-cosmeticos/natds-js-examples/tree/master/examples/single-spa/root

## Code reference

https://github.com/natura-cosmeticos/natds-js-examples/blob/9281f13bec7e2fbbf98488a5c86dfd607a4621f6/examples/single-spa/root/src/root-config.js#L4

https://github.com/natura-cosmeticos/natds-js-examples/blob/9281f13bec7e2fbbf98488a5c86dfd607a4621f6/examples/single-spa/root/src/index.ejs#L23-L37

## Current behavior

I find this on browser console:

```
single-spa-layout.min.js:2 Uncaught (in promise) Error: single-spa-layout: The HTMLElement passed to constructRoutes must be <single-spa-router>. Received TEMPLATE
    at single-spa-layout.min.js:2
    at __WEBPACK_DYNAMIC_EXPORT__../node_modules/single-spa-layout/dist/umd/single-spa-layout.min.js.e.constructRoutes (single-spa-layout.min.js:2)
    at Module../src/root-config.js (root-config.js:4)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (react-mf-root-config.js:9857)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at Object.execute (bootstrap:83)
    at i (system-core.js:274)
    at e (system-core.js:270)
```

<details>
<summary>Complete trace</summary>

```
(anonymous) @ single-spa-layout.min.js:2
__WEBPACK_DYNAMIC_EXPORT__../node_modules/single-spa-layout/dist/umd/single-spa-layout.min.js.e.constructRoutes @ single-spa-layout.min.js:2
./src/root-config.js @ root-config.js:4
__webpack_require__ @ bootstrap:19
0 @ react-mf-root-config.js:9857
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
execute @ bootstrap:83
i @ system-core.js:274
e @ system-core.js:270
(anonymous) @ system-core.js:219
load (async)
(anonymous) @ script-load.js:31
w.instantiate @ script-load.js:26
n.instantiate @ module-types.js:97
a.instantiate @ amd.js:85
(anonymous) @ system-core.js:87
Promise.then (async)
t @ system-core.js:86
(anonymous) @ system-core.js:141
Promise.then (async)
(anonymous) @ system-core.js:140
(anonymous) @ system-core.js:137
Promise.then (async)
t @ system-core.js:136
(anonymous) @ system-core.js:37
Promise.then (async)
w.import @ system-core.js:36
o.import @ global.js:47
(anonymous) @ (index):41
client:52 [WDS] Live Reloading enabled.
```

</details>

**Comment by joeldenning** [comment]
This means that you have not installed the latest beta version of single-spa-layout. Please run `npm install --save single-spa-layout@beta` instead, which will install single-spa-layout@1.0.0-beta.4. The example project you referenced currently has single-spa-layout@1.0.0 instead.

https://github.com/natura-cosmeticos/natds-js-examples/blob/9281f13bec7e2fbbf98488a5c86dfd607a4621f6/examples/single-spa/root/package.json#L12

This need to use the beta version is documented at https://single-spa.js.org/docs/layout-overview#installation.

I am closing this issue since I've provided instructions to fix this, but feel free to comment further or reopen.

**Comment by jimmyandrade** [comment]
@joeldenning 

Sorry for the delay! Now I am resuming the project, and I will take the opportunity to follow your instructions and check if everything is right now. Thank you! 😄
