### ISSUE TITLE
LayoutEngine: route matching with only trailing "/"

### ISSUE THREAD

**Issue by kbrah** [single-spa/single-spa-layout#64]
**Describe the bug or question**
When defining base path of  "/something" and route path of "/", the route will only match to "/something/" and not "/something". Since route does not allow empty strings as a route.

**Expected behavior**
route "/something" will match

**Screenshots and/or console output**
If applicable, add screenshots or console output to help explain your problem.

**Additional context**
Why is empty route string not allowed when according to documentation leading and trailing slashes are not needed?

**Comment by joeldenning** [comment]
Thanks for the bug report - I've submitted a fix in #65. I'll post here once the fix is released.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.0.0-beta.7
