### ISSUE TITLE
Uncaught Type error in constructLayoutEngine

### ISSUE THREAD

**Issue by vegard-st1** [single-spa/single-spa-layout#76]
When I try to call:

`constructLayoutEngine({ routes, applications})`

I get the following error from in the call:
```
 TypeError: (0 , e.addErrorHandler) is not a function
    at Object.activate (single-spa-layout.min.js:formatted:1)
    at HTMLElement.connectedCallback (single-spa-layout.min.js:formatted:1)
```

Dependencies: "single-spa": "^5.6.1", "single-spa-layout": "^1.0.1"

Could it be that using parcel js v1.12.4 somehow creates bad references, or might there be something else at the source?

**Comment by joeldenning** [comment]
Hmm it might be related to parcel. Could you provide a repository demonstrating the issue?

**Comment by vegard-st1** [comment]
When upgrading to the version 2 of parcel these issues disappear. I will close it here and report with them if something similar happens. Thanks for your time!

**Comment by joeldenning** [comment]
Glad to hear you got it working.
