### ISSUE TITLE
Package.json main prop is incorrect

### ISSUE THREAD

**Issue by vegard-st1** [single-spa/single-spa-layout#79]
I think it should be: "main": "dist/umd/single-spa-layout.min.cjs"

Noticed the issue using parcel version 2 because it tries to use the main as an entry point to the module.

**Comment by joeldenning** [comment]
Oops, yes this is a bug that snuck into the 1.0.0 release. Mostly I've been relying on the `exports` field in the package.json instead of the `main` field, which is why this went undetected. I have put together a fix at #81 and will publish a new version with it shortly.

**Comment by joeldenning** [comment]
This is fixed in #81 and released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.1.0
