### ISSUE TITLE
If route is wrong then it should show 404 page, which is not showing.

### ISSUE THREAD

**Issue by kush1995ptl** [single-spa/single-spa-layout#85]
Hi,
I have a route as 'http://localhost:4400/login' then it is showing login micro front end as expected, but when I am entering 'http://localhost:4400/login/timepass' then also it is showing login micro front end. It should show 404 content. I have given "Not found" as a default route still it is not working. I have attached necessary screenshots for the same.

![login](https://user-images.githubusercontent.com/26465600/97140670-27c04a00-1783-11eb-85dc-ebe3bdd606aa.png)
<img width="745" alt="timepass" src="https://user-images.githubusercontent.com/26465600/97140679-2b53d100-1783-11eb-9753-e9396bab67b5.png">
<img width="615" alt="404" src="https://user-images.githubusercontent.com/26465600/97140695-33137580-1783-11eb-93d6-c0b2bbcd89ab.png">

**Comment by joeldenning** [comment]
Hi @kush1995ptl, this is expected behavior, since the `path` attribute in `<route>` elements is a path **prefix**, not an exact match. I will update the documentation to be more clear about this.

**Comment by joeldenning** [comment]
I have clarified the documentation in https://github.com/single-spa/single-spa-layout/issues/85
