### ISSUE TITLE
Dynamic HTML layout rendering (Error: The HTMLElement passed to constructRoutes must be <single-spa-router> or a <template>)

### ISSUE THREAD

**Issue by ashok-damani** [single-spa/single-spa-layout#92]
Hi, I have used Single-Spa and its LayoutEngine framework to implement micro-frontend architecture as below

**HTML Template**
```
<template id="single-spa-layout">
      <single-spa-router>
          <application name="app1"></application>
      </single-spa-router>
</template>

```
**JS**
```
Promise.all([System.import('single-spa'), System.import('single-spa-layout')]).then(([singleSpa, singleSpaLayout]) => {
    const { constructApplications, constructLayoutEngine, constructRoutes } = singleSpaLayout;
    const { registerApplication, start } = singleSpa;
    const routes = constructRoutes(document.querySelector('#single-spa-layout'));
   const applications = constructApplications({
      routes,
      loadApp({ name }) {
        return System.import(name);
      },
    });
    const layoutEngine = constructLayoutEngine({ routes, applications });
    applications.forEach(registerApplication);
    start();
  });
```
It's working fine, but my requirement is to not to hardcode the HTML Template in root application, instead I need this to come from my backend API (server), where I would be generating different HTML Templates and in root app, I will need to fetch specific HTML Layout Template and load my micro frontend applications within this layout.

To do so, I found a link for javascript construction of HTML Elements from string (the string would come from server)
 (https://single-spa.js.org/docs/layout-definition/#html-layouts)
Where I followed the sample code as below
```
const doc = new DOMParser().parseFromString(`
<single-spa-router>
  <div class="main-content">
      <application name="app1"></application>
  </div>
</single-spa-router>
`, "text/html").documentElement;

    const routes = constructRoutes(doc);
    const applications = constructApplications({
      routes,
      loadApp({ name }) {
        return System.import(name);
      },
    });
    const layoutEngine = constructLayoutEngine({ routes, applications });
    applications.forEach(registerApplication);
    start();
```

But I am getting below error
**zone.js:690 Unhandled Promise rejection: single-spa-layout: The HTMLElement passed to constructRoutes must be <single-spa-router> or a <template> containing the router. Received HTML ; Zone: <root> ; Task: Promise.then ; Value: Error: single-spa-layout: The HTMLElement passed to constructRoutes must be <single-spa-router> or a <template> containing the router.**

**Comment by joeldenning** [comment]
Hi @ashok-damani, the issue here is that `doc` references the documentElement instead of the single-spa-router element. To fix, you should `doc.querySelector('single-spa-router')`

```js
const doc = new DOMParser().parseFromString(`
<single-spa-router>
  <div class="main-content">
      <application name="app1"></application>
  </div>
</single-spa-router>
`, "text/html").documentElement;

    const routes = constructRoutes(doc.querySelector('single-spa-router'));
    const applications = constructApplications({
      routes,
      loadApp({ name }) {
        return System.import(name);
      },
    });
    const layoutEngine = constructLayoutEngine({ routes, applications });
    applications.forEach(registerApplication);
    start();
```

Closing this since I believe to have answered the question, but feel free to comment further or reopen.

**Comment by joeldenning** [comment]
I've updated the documentation to make this more clear:

https://github.com/single-spa/single-spa.js.org/commit/d887bc31ac39cd351d3daa3dda0393f3b12e603d

**Comment by ashok-damani** [comment]
@joeldenning  Thank you
